// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTAdBGtEdGPIh0CT_y7z1xe3icSmRY2I',
    appId: '1:1071345974950:web:ce5b0defb3b87db8763e67',
    messagingSenderId: '1071345974950',
    projectId: 'jaipoc-ecb72',
    authDomain: 'jaipoc-ecb72.firebaseapp.com',
    storageBucket: 'jaipoc-ecb72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Jf4EGNXtD4bfdYfa9aChQgY9jsBuxXk',
    appId: '1:1071345974950:android:c642ea4c714bd550763e67',
    messagingSenderId: '1071345974950',
    projectId: 'jaipoc-ecb72',
    storageBucket: 'jaipoc-ecb72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH5E8FTRcR3ydvO9gJeJMNAQOsLCor6kw',
    appId: '1:1071345974950:ios:5c7b5d8b74f4c9ff763e67',
    messagingSenderId: '1071345974950',
    projectId: 'jaipoc-ecb72',
    storageBucket: 'jaipoc-ecb72.appspot.com',
    iosBundleId: 'com.example.jaiPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH5E8FTRcR3ydvO9gJeJMNAQOsLCor6kw',
    appId: '1:1071345974950:ios:0ebb32d25a7cec94763e67',
    messagingSenderId: '1071345974950',
    projectId: 'jaipoc-ecb72',
    storageBucket: 'jaipoc-ecb72.appspot.com',
    iosBundleId: 'com.example.jaiPoc.RunnerTests',
  );
}
